plugins {
    id 'application'
    id 'java'
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
    // Dropwizard dependencies
    implementation platform('io.dropwizard:dropwizard-bom:2.1.4')
    implementation 'io.dropwizard:dropwizard-core'
    implementation 'io.dropwizard:dropwizard-client'
    
    // Testing
    testImplementation 'io.dropwizard:dropwizard-testing'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.2'
}

application {
    mainClass = 'org.example.app.App'
}

run {
    args = ['server', './config.yml']
}

test {
    useJUnitPlatform()
}
