# Server configuration
server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

# Application-specific configuration
app:
  revision: "0000"

logging:
  level: INFO
  loggers:
    org.example.app: DEBUG
  appenders:
    - type: console
      logFormat: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Metrics configuration
metrics:
  reporters:
    - type: graphite
      host: localhost
      port: 2003
      prefix: dropwizard-service
      durationUnit: seconds
      rateUnit: seconds
      frequency: 60s


